
/* Drop Indexes */

DROP INDEX IDX_TBOARD_REFSTEP_UK;
DROP INDEX IDX_TLECTURE_NU;



/* Drop Views */

DROP VIEW VPRCHS_ACCM;



/* Drop Tables */

DROP TABLE TACCM_PNT;
DROP TABLE TBOARD;
DROP TABLE TCODE;
DROP TABLE TCSMT_OPT;
DROP TABLE TPRCHS_OPT;
DROP TABLE TPRCHS_DET;
DROP TABLE TCSMT;
DROP TABLE TLECTURE_APP;
DROP TABLE TLECTURE;
DROP TABLE TLECTURE_REQ;
DROP TABLE TMCODE;
DROP TABLE TPRCHS;
DROP TABLE TUSER_LOG;
DROP TABLE TUSER;



/* Drop Sequences */

DROP SEQUENCE YTEDU.TBANK_ACC_SEQ;
DROP SEQUENCE YTEDU.TBOARD_SEQ;
DROP SEQUENCE YTEDU.TLECTURE_REQ_SEQ;
DROP SEQUENCE YTEDU.TLECTURE_SEQ;
DROP SEQUENCE YTEDU.TPRCHS_SEQ;




/* Create Tables */

-- 적립금상세
CREATE TABLE TACCM_PNT
(
	-- 사용자아이디
	USER_ID VARCHAR2(50) NOT NULL,
	-- 구매일련번호
	-- 상품아이디(7)-년월일(8)-일련번호(5)
	PRCHS_SEQ_NO VARCHAR2(50) NOT NULL,
	-- 적립금
	ACCM_PNT NUMBER(15,0) DEFAULT 0 NOT NULL,
	-- 적립일
	ACCM_DATE DATE DEFAULT SYSDATE NOT NULL,
	-- 적립구분
	-- 1 수동
	-- 2 자동
	ACCM_TYPE_CD CHAR(1) DEFAULT '1',
	-- 정산여부
	STLMNT_YN CHAR(1) DEFAULT '0' NOT NULL,
	-- 정산일
	STLMNT_DATE DATE,
	CONSTRAINT IDX_TACCM_PNT_PK PRIMARY KEY (USER_ID, PRCHS_SEQ_NO)
);


CREATE TABLE TBOARD
(
	-- 분류
	-- CM   사이트(NOTICE, QNA, 일반)
	-- IT     INTRODUCE
	-- EL    E-LEARNING
	-- 
	CATEGORY VARCHAR2(2) NOT NULL,
	-- 하위분류
	SUB_CATEGORY VARCHAR2(2) NOT NULL,
	-- 일련번호
	SEQ_NO NUMBER(15,0) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	-- 내용
	CONTENT VARCHAR2(4000) NOT NULL,
	-- 첨부데이터1
	APPND_DATA1 VARCHAR2(100),
	-- 첨부데이터2
	APPND_DATA2 VARCHAR2(100),
	-- 첨부데이터3
	APPND_DATA3 VARCHAR2(100),
	-- 등록자아이디
	REG_ID VARCHAR2(50) NOT NULL,
	-- REG_PASS
	REG_PASS VARCHAR2(50),
	-- 등록일시
	REG_DATE DATE DEFAULT SYSDATE NOT NULL,
	-- 조회횟수
	READ_CNT NUMBER(10,0) DEFAULT 0 NOT NULL,
	-- 원본
	REF_NO NUMBER(15,0) NOT NULL,
	-- 답글스텝
	RE_STEP NUMBER(10,0) DEFAULT 0 NOT NULL,
	-- 답글레벨
	RE_LEVEL NUMBER(10,0) DEFAULT 0 NOT NULL,
	CONSTRAINT IDX_TBOARD_PK PRIMARY KEY (CATEGORY, SUB_CATEGORY, SEQ_NO)
);


CREATE TABLE TCODE
(
	-- 마스터코드
	MCODE_CD VARCHAR2(15) NOT NULL,
	-- 상세코드
	DCODE_CD VARCHAR2(15) NOT NULL,
	-- 코드명1
	CODE_NM1 VARCHAR2(100) NOT NULL,
	-- 코드명2
	CODE_NM2 VARCHAR2(100),
	-- 코드명3
	CODE_NM3 VARCHAR2(100),
	-- 코드명4
	CODE_NM4 VARCHAR2(100),
	-- 코드명5
	CODE_NM5 VARCHAR2(100),
	-- 코드명6
	CODE_NM6 VARCHAR2(100),
	-- 정렬순서
	ORDER_NO NUMBER(3,0),
	CONSTRAINT IDX_TCODE_PK PRIMARY KEY (MCODE_CD, DCODE_CD)
);


CREATE TABLE TCSMT
(
	-- 미용상품아이디
	-- 상품코드(2)+일련번호(5)
	CSMT_ID VARCHAR2(15) NOT NULL,
	-- 미용상품종류코드
	CSMT_KIND_CD VARCHAR2(2) NOT NULL,
	-- 미용상품명
	CSMT_NAME VARCHAR2(50) NOT NULL,
	-- 미용상품이미지
	CSMT_IMG VARCHAR2(100),
	-- 미용상품설명
	CSMT_DESC VARCHAR2(4000) NOT NULL,
	-- 미용상품설명이미지1
	CSMT_DESC_IMG1 VARCHAR2(100),
	-- 상품설명이미지2
	CSMT_DESC_IMG2 VARCHAR2(100),
	-- 미용상품설명이미지3
	CSMT_DESC_IMG3 VARCHAR2(100),
	-- 미용상품등록일
	CSMT_REG_YMD DATE DEFAULT SYSDATE NOT NULL,
	-- 미용상품가격
	CSMT_PRICE NUMBER(10,0) DEFAULT 0 NOT NULL,
	-- 미용상품재고수
	CSMT_STOCK NUMBER(10,0) DEFAULT 0 NOT NULL,
	-- 제조회사명
	PUB_COMP VARCHAR2(100),
	-- 제조년월일
	PUB_DATE DATE,
	-- 입금방법
	PAY_DESC VARCHAR2(2000),
	-- 입금방법이미지
	PAY_DESC_IMG VARCHAR2(100),
	-- 조회횟수
	READ_CNT NUMBER(10,0) DEFAULT 0,
	-- 삭제플래그
	DLT_FLG CHAR(1) DEFAULT '0',
	CONSTRAINT IDX_TCSMT_PK PRIMARY KEY (CSMT_ID)
);


CREATE TABLE TCSMT_OPT
(
	-- 미용상품아이디
	CSMT_ID VARCHAR2(15) NOT NULL,
	-- 미용상품옵션코드
	CSMT_OPT_CD VARCHAR2(15) NOT NULL,
	-- 비고
	RMRKS VARCHAR2(500),
	CONSTRAINT IDX_TCSMT_OPT_PK PRIMARY KEY (CSMT_ID, CSMT_OPT_CD)
);


CREATE TABLE TLECTURE
(
	-- 교육일련번호
	LEC_SEQ_NO NUMBER(15,0) NOT NULL,
	-- 교육상태코드
	-- 1 요청
	-- 9 종료
	LEC_STAT_CD CHAR(1) NOT NULL,
	-- 교육제목
	LEC_TITLE VARCHAR2(300) NOT NULL,
	-- 교육주체(가맹점명)
	LEC_HOST VARCHAR2(100) NOT NULL,
	-- 교육시작일시
	LEC_ST_DATE VARCHAR2(10) NOT NULL,
	-- 교육종료일시
	LEC_ED_DATE VARCHAR2(10) NOT NULL,
	-- 교육시간
	LEC_TIME VARCHAR2(50) NOT NULL,
	-- 교육설명
	LEC_DESC VARCHAR2(4000) NOT NULL,
	-- 교육설명이미지
	LEC_DESC_IMG VARCHAR2(100),
	-- 교육장소
	LEC_LOC VARCHAR2(200) NOT NULL,
	-- 교육인원수
	LEC_MAN_CT NUMBER(5,0),
	-- 교육과목
	LEC_SUBJ VARCHAR2(100),
	-- 교육요청일련번호
	LEC_REQ_NO NUMBER(15,0) DEFAULT 0 NOT NULL,
	-- 조회횟수
	READ_CNT NUMBER(10,0) DEFAULT 0 NOT NULL,
	-- 등록일시
	REG_DATE DATE DEFAULT SYSDATE NOT NULL,
	-- 삭제플래그
	DLT_FLG CHAR(1) DEFAULT '0' NOT NULL,
	CONSTRAINT IDX_TLECTURE_PK PRIMARY KEY (LEC_SEQ_NO)
);


CREATE TABLE TLECTURE_APP
(
	-- 교육일련번호
	LEC_SEQ_NO NUMBER(15,0) NOT NULL,
	-- 사용자아이디
	USER_ID VARCHAR2(50) NOT NULL,
	-- 신청일시
	APP_DATE DATE DEFAULT SYSDATE,
	-- 신청상태코드
	-- 1 신청
	-- 2 승인
	-- 3 미승인
	-- 9 본인취소
	APP_STAT_CD CHAR(1) DEFAULT '1',
	-- 비고
	RMRKS VARCHAR2(500),
	CONSTRAINT IDX_TLECTURE_APP_PK PRIMARY KEY (LEC_SEQ_NO, USER_ID)
);


CREATE TABLE TLECTURE_REQ
(
	-- 교육요청일련번호
	LEC_REQ_NO NUMBER(15,0) NOT NULL,
	-- 교육요청제목
	LEC_REQ_TITLE VARCHAR2(300) NOT NULL,
	-- 교육요청내용
	LEC_REQ_DESC VARCHAR2(4000) NOT NULL,
	-- 교육요청아이디
	LEC_REQ_ID VARCHAR2(50) NOT NULL,
	-- 교육요청패스워드
	LEC_REQ_PASS VARCHAR2(50),
	-- 교육요청일시
	LEC_REQ_DATE DATE DEFAULT SYSDATE NOT NULL,
	-- 삭제플래그
	DLT_FLG CHAR(1) DEFAULT '0',
	CONSTRAINT IDX_TLECTURE_REQ_PK PRIMARY KEY (LEC_REQ_NO)
);


CREATE TABLE TMCODE
(
	-- 마스터코드
	MCODE_CD VARCHAR2(15) NOT NULL,
	-- 마스터코드명
	MCODE_NM VARCHAR2(100) NOT NULL,
	-- 비고
	RMRKS VARCHAR2(500),
	CONSTRAINT IDX_TMCODE_PK PRIMARY KEY (MCODE_CD)
);


CREATE TABLE TPRCHS
(
	-- 구매일련번호
	-- 상품아이디(7)-년월일(8)-일련번호(5)
	PRCHS_SEQ_NO VARCHAR2(50) NOT NULL,
	-- 구매자아이디
	PRCHS_USER_ID VARCHAR2(50) NOT NULL,
	-- 구매일시
	PRCHS_DATE DATE DEFAULT SYSDATE NOT NULL,
	-- 구매상태코드
	-- 1 구매신청
	-- 2 입금대기
	-- 3 배송완료
	-- 4 구매완료
	-- 9 구매취소
	PRCHS_STAT_CD CHAR(1) DEFAULT '1' NOT NULL,
	-- 구매가격
	PRCHS_PRICE NUMBER(15,0) NOT NULL,
	-- 구매개수
	PRCHS_CNT NUMBER(5,0) DEFAULT 0 NOT NULL,
	-- 입금계좌
	PAY_ACC VARCHAR2(200),
	-- 수취인명
	DLVR_NAME VARCHAR2(100) NOT NULL,
	-- 배송전화번호
	DLVR_PHONE VARCHAR2(20) NOT NULL,
	-- 배송주소
	DLVR_ADDR VARCHAR2(200) NOT NULL,
	-- 배송일시
	DLVR_DATE DATE,
	-- 배송완료일시
	DLVR_COMP_DATE DATE,
	-- 구매완료일시
	PRCHS_COMP_DATE DATE,
	-- 구매취소일시
	PRCHS_CNCL_DATE DATE,
	-- 비고
	RMRKS VARCHAR2(500),
	-- 삭제플래그
	DLT_FLG CHAR(1) DEFAULT '0',
	CONSTRAINT IDX_TPRCHS_PK PRIMARY KEY (PRCHS_SEQ_NO)
);


CREATE TABLE TPRCHS_DET
(
	-- 구매일련번호
	-- 상품아이디(7)-년월일(8)-일련번호(5)
	PRCHS_SEQ_NO VARCHAR2(50) NOT NULL,
	-- 구매그룹번호
	PRCHS_GRP_NO NUMBER(5,0) NOT NULL,
	-- 0 : 구매기본
	-- 1 : 옵션구매
	-- 2 : 추가구매
	PRCHS_GRP_CD CHAR(1) NOT NULL,
	-- 미용상품아이디
	-- 상품코드(2)+일련번호(5)
	CSMT_ID VARCHAR2(15) NOT NULL,
	-- 미용상품개수
	CSMT_CNT NUMBER(5,0) NOT NULL,
	-- 합계가격
	TTL_PRICE NUMBER(15,0) DEFAULT 0 NOT NULL,
	-- 구매그룹내용
	PRCHS_GRP_DESC VARCHAR2(500),
	CONSTRAINT IDX_TPRCHS_DET_PK PRIMARY KEY (PRCHS_SEQ_NO, PRCHS_GRP_NO)
);


CREATE TABLE TPRCHS_OPT
(
	-- 구매일련번호
	-- 상품아이디(7)-년월일(8)-일련번호(5)
	PRCHS_SEQ_NO VARCHAR2(50) NOT NULL,
	-- 구매그룹번호
	PRCHS_GRP_NO NUMBER(5,0) NOT NULL,
	-- 구매옵션M코드
	PRCHS_OPT_MCD VARCHAR2(15) NOT NULL,
	-- 구매옵션D코드
	PRCHS_OPT_DCD VARCHAR2(15) NOT NULL,
	CONSTRAINT IDX_TPRCHS_OPT_PK PRIMARY KEY (PRCHS_SEQ_NO, PRCHS_GRP_NO, PRCHS_OPT_MCD)
);


-- 유저테이블
CREATE TABLE TUSER
(
	-- 사용자아이디
	USER_ID VARCHAR2(50) NOT NULL,
	-- 사용자암호
	USER_PASS VARCHAR2(50) NOT NULL,
	-- 사용자이름
	USER_NAME VARCHAR2(100) NOT NULL,
	-- 가맹점명
	AGENCY_NAME VARCHAR2(100) NOT NULL,
	-- 추천인아이디
	RCMMD_ID VARCHAR2(50) NOT NULL,
	-- 계층아이디
	FAMILY_ID VARCHAR2(50) NOT NULL CONSTRAINT IDX_FAMILY_ID_UK UNIQUE,
	-- 휴대폰번호
	CELL_PHONE VARCHAR2(20),
	-- 전화번호
	PHONE VARCHAR2(20),
	-- 이메일
	EMAIL VARCHAR2(100) NOT NULL,
	-- 우편번호
	ZIPCODE VARCHAR2(10) NOT NULL,
	-- 주소
	ADDR VARCHAR2(200) NOT NULL,
	-- 사용자등급
	GRADE CHAR(1) DEFAULT '4' NOT NULL,
	-- 등록일시
	REG_DATE DATE DEFAULT SYSDATE NOT NULL,
	-- 삭제플래그
	DLT_FLG CHAR(1) DEFAULT '0' NOT NULL,
	CONSTRAINT IDX_TUSER_PK PRIMARY KEY (USER_ID)
);


CREATE TABLE TUSER_LOG
(
	-- 사용자아이디
	USER_ID VARCHAR2(50) NOT NULL,
	ACCS_DATE DATE DEFAULT SYSDATE NOT NULL,
	-- 액세스타입코드
	-- 01 로그인
	-- 02 로그아웃
	-- 03 중복로그인에의한 강제 로그아웃
	-- 04 타임아웃
	-- 05 동영상스트리밍
	-- 06 상품조회
	ACSS_TYPE_CD CHAR(2),
	-- 액세스대상
	ACSS_TRG VARCHAR2(500),
	-- 액세스아이피
	ACSS_IP VARCHAR2(50) DEFAULT '0.0.0.0' NOT NULL,
	CONSTRAINT IDX_TUSER_LOG_PK PRIMARY KEY (USER_ID, ACCS_DATE)
);



/* Create Views */

CREATE VIEW VPRCHS_ACCM AS SELECT PR.PRCHS_SEQ_NO,
    PR.PRCHS_USER_ID,
    U1.USER_NAME,
    U1.AGENCY_NAME,
    U1.FAMILY_ID,
    U1.GRADE,
    C1.CODE_NM1 AS GRADE_NAME,
    U1.RCMMD_ID,
    U2.USER_NAME   AS RCMMD_NAME,
    U2.AGENCY_NAME AS RCMMD_AGENCY_NAME,
    U2.FAMILY_ID   AS RCMMD_FAMILY_ID,
    U2.GRADE       AS RCMMD_GRADE,
    C2.CODE_NM1    AS RCMMD_GRADE_NAME,
    PR.PRCHS_DATE,
    PR.PRCHS_STAT_CD,
    C3.CODE_NM1 AS PRCHS_STAT_NAME,
    CS.CSMT_ID,
    CS.CSMT_KIND_CD,
    CS.CSMT_NAME,
    CS.CSMT_IMG,
    CS.CSMT_DESC,
    CS.CSMT_REG_YMD,
    CS.PUB_COMP,
    CS.PUB_DATE,
    CS.CSMT_PRICE,
    PR.PRCHS_PRICE,
    PR.PRCHS_CNT,
    DT.PRCHS_DET AS PRCHS_DET,
    PR.PAY_ACC,
    PR.DLVR_NAME,
    PR.DLVR_PHONE,
    PR.DLVR_ADDR,
    PR.DLVR_DATE,
    PR.DLVR_COMP_DATE,
    PR.PRCHS_COMP_DATE,
    PR.PRCHS_CNCL_DATE,
    PR.RMRKS,
    NVL(PR.PRCHS_PRICE * TO_NUMBER(C1.CODE_NM2) / 100, 0) AS AGENCY_ACCM_PNT,
    NVL(PR.PRCHS_PRICE * TO_NUMBER(C1.CODE_NM3) / 100, 0) AS SUBAGENCY_ACCM_PNT,
    NVL(PR.PRCHS_PRICE * TO_NUMBER(C1.CODE_NM4) / 100, 0) AS SUPAGENCY_ACCM_PNT
  FROM TPRCHS PR
  JOIN TCSMT CS
  ON CS.CSMT_ID = SUBSTR(PR.PRCHS_SEQ_NO,1,7)
  JOIN TUSER U1
  ON PR.PRCHS_USER_ID = U1.USER_ID
  JOIN TUSER U2
  ON U1.RCMMD_ID = U2.USER_ID
  LEFT JOIN
    (SELECT PRCHS_SEQ_NO,
      TRIM(':'
    FROM MAX(SYS_CONNECT_BY_PATH(TRIM(PRCHS_GRP_DESC)
      ||DECODE(PRCHS_GRP_CD, 'O', '', '('
      ||CSMT_ID
      ||')')
      ||','
      ||CSMT_CNT
      ||','
      ||TTL_PRICE, ':'))) AS PRCHS_DET
    FROM
      (SELECT PRCHS_SEQ_NO,
        PRCHS_GRP_NO,
        PRCHS_GRP_CD,
        CSMT_ID,
        CSMT_CNT,
        TTL_PRICE,
        PRCHS_GRP_DESC,
        ROW_NUMBER() OVER(PARTITION BY PRCHS_SEQ_NO ORDER BY PRCHS_GRP_NO) AS RN
      FROM TPRCHS_DET
      )
      START WITH RN                 = 1
      CONNECT BY PRIOR PRCHS_SEQ_NO = PRCHS_SEQ_NO
    AND PRIOR RN                    = RN - 1
    GROUP BY PRCHS_SEQ_NO
    ) DT
  ON PR.PRCHS_SEQ_NO = DT.PRCHS_SEQ_NO
  LEFT JOIN TCODE C1
  ON U1.GRADE     = C1.DCODE_CD
  AND C1.MCODE_CD = 'CM001'
  LEFT JOIN TCODE C2
  ON U2.GRADE     = C2.DCODE_CD
  AND C2.MCODE_CD = 'CM001'
  LEFT JOIN TCODE C3
  ON PR.PRCHS_STAT_CD = C3.DCODE_CD
  AND C3.MCODE_CD     = 'ES002'
  WHERE PR.DLT_FLG    = '0';



/* Create Indexes */

CREATE UNIQUE INDEX IDX_TBOARD_REFSTEP_UK ON TBOARD (CATEGORY, SUB_CATEGORY, REF_NO, RE_STEP);
CREATE INDEX IDX_TLECTURE_NU ON TLECTURE (LEC_STAT_CD, DLT_FLG);



/* Comments */

COMMENT ON TABLE TACCM_PNT IS '적립금상세';
COMMENT ON COLUMN TACCM_PNT.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TACCM_PNT.PRCHS_SEQ_NO IS '구매일련번호';
COMMENT ON COLUMN TACCM_PNT.ACCM_PNT IS '적립금';
COMMENT ON COLUMN TACCM_PNT.ACCM_DATE IS '적립일';
COMMENT ON COLUMN TACCM_PNT.ACCM_TYPE_CD IS '적립구분';
COMMENT ON COLUMN TACCM_PNT.STLMNT_YN IS '정산여부';
COMMENT ON COLUMN TACCM_PNT.STLMNT_DATE IS '정산일';
COMMENT ON TABLE TBOARD IS '게시판';
COMMENT ON COLUMN TBOARD.CATEGORY IS '분류';
COMMENT ON COLUMN TBOARD.SUB_CATEGORY IS '하위분류';
COMMENT ON COLUMN TBOARD.SEQ_NO IS '일련번호';
COMMENT ON COLUMN TBOARD.TITLE IS '제목';
COMMENT ON COLUMN TBOARD.CONTENT IS '내용';
COMMENT ON COLUMN TBOARD.APPND_DATA1 IS '첨부데이터1';
COMMENT ON COLUMN TBOARD.APPND_DATA2 IS '첨부데이터2';
COMMENT ON COLUMN TBOARD.APPND_DATA3 IS '첨부데이터3';
COMMENT ON COLUMN TBOARD.REG_ID IS '등록자아이디';
COMMENT ON COLUMN TBOARD.REG_PASS IS '등록암호';
COMMENT ON COLUMN TBOARD.REG_DATE IS '등록일시';
COMMENT ON COLUMN TBOARD.READ_CNT IS '조회횟수';
COMMENT ON COLUMN TBOARD.REF_NO IS '원본';
COMMENT ON COLUMN TBOARD.RE_STEP IS '답글스텝';
COMMENT ON COLUMN TBOARD.RE_LEVEL IS '답글레벨';
COMMENT ON TABLE TCODE IS '상세코드테이블';
COMMENT ON COLUMN TCODE.MCODE_CD IS '마스터코드';
COMMENT ON COLUMN TCODE.DCODE_CD IS '상세코드';
COMMENT ON COLUMN TCODE.CODE_NM1 IS '코드명1';
COMMENT ON COLUMN TCODE.CODE_NM2 IS '코드명2';
COMMENT ON COLUMN TCODE.CODE_NM3 IS '코드명3';
COMMENT ON COLUMN TCODE.CODE_NM4 IS '코드명4';
COMMENT ON COLUMN TCODE.CODE_NM5 IS '코드명5';
COMMENT ON COLUMN TCODE.CODE_NM6 IS '코드명6';
COMMENT ON COLUMN TCODE.ORDER_NO IS '정렬순서';
COMMENT ON TABLE TCSMT IS '미용상품';
COMMENT ON COLUMN TCSMT.CSMT_ID IS '미용상품아이디';
COMMENT ON COLUMN TCSMT.CSMT_KIND_CD IS '미용상품종류코드';
COMMENT ON COLUMN TCSMT.CSMT_NAME IS '미용상품명';
COMMENT ON COLUMN TCSMT.CSMT_IMG IS '미용상품이미지';
COMMENT ON COLUMN TCSMT.CSMT_DESC IS '미용상품설명';
COMMENT ON COLUMN TCSMT.CSMT_DESC_IMG1 IS '미용상품설명이미지1';
COMMENT ON COLUMN TCSMT.CSMT_DESC_IMG2 IS '미용상품설명이미지2';
COMMENT ON COLUMN TCSMT.CSMT_DESC_IMG3 IS '미용상품설명이미지3';
COMMENT ON COLUMN TCSMT.CSMT_REG_YMD IS '미용상품등록일';
COMMENT ON COLUMN TCSMT.CSMT_PRICE IS '미용상품가격';
COMMENT ON COLUMN TCSMT.CSMT_STOCK IS '미용상품재고수';
COMMENT ON COLUMN TCSMT.PUB_COMP IS '제조회사명';
COMMENT ON COLUMN TCSMT.PUB_DATE IS '제조년월일';
COMMENT ON COLUMN TCSMT.PAY_DESC IS '입금방법';
COMMENT ON COLUMN TCSMT.PAY_DESC_IMG IS '입금방법이미지';
COMMENT ON COLUMN TCSMT.READ_CNT IS '조회횟수';
COMMENT ON COLUMN TCSMT.DLT_FLG IS '삭제플래그';
COMMENT ON TABLE TCSMT_OPT IS '미용상품옵션';
COMMENT ON COLUMN TCSMT_OPT.CSMT_ID IS '미용상품아이디';
COMMENT ON COLUMN TCSMT_OPT.CSMT_OPT_CD IS '미용상품옵션코드';
COMMENT ON COLUMN TCSMT_OPT.RMRKS IS '비고';
COMMENT ON TABLE TLECTURE IS '미용교육';
COMMENT ON COLUMN TLECTURE.LEC_SEQ_NO IS '교육일련번호';
COMMENT ON COLUMN TLECTURE.LEC_STAT_CD IS '교육상태코드';
COMMENT ON COLUMN TLECTURE.LEC_TITLE IS '교육제목';
COMMENT ON COLUMN TLECTURE.LEC_HOST IS '교육주체';
COMMENT ON COLUMN TLECTURE.LEC_ST_DATE IS '교육시작일시';
COMMENT ON COLUMN TLECTURE.LEC_ED_DATE IS '교육종료일시';
COMMENT ON COLUMN TLECTURE.LEC_TIME IS '교육시간';
COMMENT ON COLUMN TLECTURE.LEC_DESC IS '교육설명';
COMMENT ON COLUMN TLECTURE.LEC_DESC_IMG IS '교육설명이미지';
COMMENT ON COLUMN TLECTURE.LEC_LOC IS '교육장소';
COMMENT ON COLUMN TLECTURE.LEC_MAN_CT IS '교육인원수';
COMMENT ON COLUMN TLECTURE.LEC_SUBJ IS '교육과목';
COMMENT ON COLUMN TLECTURE.LEC_REQ_NO IS '교육요청일련번호';
COMMENT ON COLUMN TLECTURE.READ_CNT IS '조회횟수';
COMMENT ON COLUMN TLECTURE.REG_DATE IS '등록일시';
COMMENT ON COLUMN TLECTURE.DLT_FLG IS '삭제플래그';
COMMENT ON TABLE TLECTURE_APP IS '미용교육신청자';
COMMENT ON COLUMN TLECTURE_APP.LEC_SEQ_NO IS '교육일련번호';
COMMENT ON COLUMN TLECTURE_APP.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TLECTURE_APP.APP_DATE IS '신청일시';
COMMENT ON COLUMN TLECTURE_APP.APP_STAT_CD IS '신청상태코드';
COMMENT ON COLUMN TLECTURE_APP.RMRKS IS '비고';
COMMENT ON TABLE TLECTURE_REQ IS '교육요청';
COMMENT ON COLUMN TLECTURE_REQ.LEC_REQ_NO IS '교육요청일련번호';
COMMENT ON COLUMN TLECTURE_REQ.LEC_REQ_TITLE IS '교육요청제목';
COMMENT ON COLUMN TLECTURE_REQ.LEC_REQ_DESC IS '교육요청내용';
COMMENT ON COLUMN TLECTURE_REQ.LEC_REQ_ID IS '교육요청아이디';
COMMENT ON COLUMN TLECTURE_REQ.LEC_REQ_PASS IS '교육요청패스워드';
COMMENT ON COLUMN TLECTURE_REQ.LEC_REQ_DATE IS '교육요청일시';
COMMENT ON COLUMN TLECTURE_REQ.DLT_FLG IS '삭제플래그';
COMMENT ON TABLE TMCODE IS '마스터코드';
COMMENT ON COLUMN TMCODE.MCODE_CD IS '마스터코드';
COMMENT ON COLUMN TMCODE.MCODE_NM IS '마스터코드명';
COMMENT ON COLUMN TMCODE.RMRKS IS '비고';
COMMENT ON TABLE TPRCHS IS '구매';
COMMENT ON COLUMN TPRCHS.PRCHS_SEQ_NO IS '구매일련번호';
COMMENT ON COLUMN TPRCHS.PRCHS_USER_ID IS '구매자아이디';
COMMENT ON COLUMN TPRCHS.PRCHS_DATE IS '구매일시';
COMMENT ON COLUMN TPRCHS.PRCHS_STAT_CD IS '구매상태코드';
COMMENT ON COLUMN TPRCHS.PRCHS_PRICE IS '구매가격';
COMMENT ON COLUMN TPRCHS.PRCHS_CNT IS '구매개수';
COMMENT ON COLUMN TPRCHS.PAY_ACC IS '입금계좌';
COMMENT ON COLUMN TPRCHS.DLVR_NAME IS '수취인명';
COMMENT ON COLUMN TPRCHS.DLVR_PHONE IS '배송전화번호';
COMMENT ON COLUMN TPRCHS.DLVR_ADDR IS '배송주소';
COMMENT ON COLUMN TPRCHS.DLVR_DATE IS '배송일시';
COMMENT ON COLUMN TPRCHS.DLVR_COMP_DATE IS '배송완료일시';
COMMENT ON COLUMN TPRCHS.PRCHS_COMP_DATE IS '구매완료일시';
COMMENT ON COLUMN TPRCHS.PRCHS_CNCL_DATE IS '구매취소일시';
COMMENT ON COLUMN TPRCHS.RMRKS IS '비고';
COMMENT ON COLUMN TPRCHS.DLT_FLG IS '삭제플래그';
COMMENT ON TABLE TPRCHS_DET IS '구매상세';
COMMENT ON COLUMN TPRCHS_DET.PRCHS_SEQ_NO IS '구매일련번호';
COMMENT ON COLUMN TPRCHS_DET.PRCHS_GRP_NO IS '구매그룹번호';
COMMENT ON COLUMN TPRCHS_DET.PRCHS_GRP_CD IS '구매그룹코드';
COMMENT ON COLUMN TPRCHS_DET.CSMT_ID IS '미용상품아이디';
COMMENT ON COLUMN TPRCHS_DET.CSMT_CNT IS '미용상품개수';
COMMENT ON COLUMN TPRCHS_DET.TTL_PRICE IS '합계가격';
COMMENT ON COLUMN TPRCHS_DET.PRCHS_GRP_DESC IS '구매그룹내용';
COMMENT ON TABLE TPRCHS_OPT IS '구매옵션';
COMMENT ON COLUMN TPRCHS_OPT.PRCHS_SEQ_NO IS '구매일련번호';
COMMENT ON COLUMN TPRCHS_OPT.PRCHS_GRP_NO IS '구매그룹번호';
COMMENT ON COLUMN TPRCHS_OPT.PRCHS_OPT_MCD IS '구매옵션M코드';
COMMENT ON COLUMN TPRCHS_OPT.PRCHS_OPT_DCD IS '구매옵션D코드';
COMMENT ON TABLE TUSER IS '유저정보';
COMMENT ON COLUMN TUSER.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TUSER.USER_PASS IS '사용자암호';
COMMENT ON COLUMN TUSER.USER_NAME IS '사용자이름';
COMMENT ON COLUMN TUSER.AGENCY_NAME IS '가맹점명';
COMMENT ON COLUMN TUSER.RCMMD_ID IS '추천인아이디';
COMMENT ON COLUMN TUSER.FAMILY_ID IS '계층아이디';
COMMENT ON COLUMN TUSER.CELL_PHONE IS '휴대폰번호';
COMMENT ON COLUMN TUSER.PHONE IS '전화번호';
COMMENT ON COLUMN TUSER.EMAIL IS '이메일';
COMMENT ON COLUMN TUSER.ZIPCODE IS '우편번호';
COMMENT ON COLUMN TUSER.ADDR IS '주소';
COMMENT ON COLUMN TUSER.GRADE IS '사용자등급';
COMMENT ON COLUMN TUSER.REG_DATE IS '등록일시';
COMMENT ON COLUMN TUSER.DLT_FLG IS '삭제플래그';
COMMENT ON TABLE TUSER_LOG IS '액세스로그';
COMMENT ON COLUMN TUSER_LOG.USER_ID IS '사용자아이디';
COMMENT ON COLUMN TUSER_LOG.ACCS_DATE IS '액세스날짜';
COMMENT ON COLUMN TUSER_LOG.ACSS_TYPE_CD IS '액세스타입코드';
COMMENT ON COLUMN TUSER_LOG.ACSS_TRG IS '액세스대상';
COMMENT ON COLUMN TUSER_LOG.ACSS_IP IS '액세스아이피';



